# Generated by Django 5.1.2 on 2025-01-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_image_url_remove_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian'), ('Dessert', 'Dessert'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='Default Recipe Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
